[[ $DEBUG_BASHRC = 1 ]] && echo "    loading fearless"

# Environment Variables --------------------------------------------------------

echo "loading fearless.conf"
export FEAR_SSH_CONFIG=${HOME}/.ssh/config-fearless
export FEARLESS_DEV=${HOME}/Documents/Fearless/dev
export GITAR=${FEARLESS_DEV}/.gitar

if [ -z $CDPATH ] ; then
  export CDPATH=.:${FEARLESS_DEV}
else
  export CDPATH=${CDPATH}:${FEARLESS_DEV}
fi

# reCAPTCHA Settings -----------------------------------------------------------

# Use this in the HTML code you site serves to users.
export RECAPTCHA_PUBLIC_KEY=6LffFggUAAAAACugCw4H1sL4jv66yaC5BNL2dqV6 # dev.solipet.me
# Use this for communication between your site and Google.
export RECAPTCHA_PRIVATE_KEY=6LffFggUAAAAAMy4V7pJiY0cZC0DziMc5uOjKVtV # dev.solipet.me

# Aliases ----------------------------------------------------------------------


# Functions --------------------------------------------------------------------

fearless-aws()
{
  export AWS_PROFILE=fearless
  echo "AWS_PROFILE=$AWS_PROFILE"
}

function runtests(){
  echo "================RUNNING RSPEC TEST======================="
  rspec -f d
  echo ""
  echo "================RUNNING RUBOCOP TEST====================="
  rubocop -f s
  echo ""
  echo "============RUNNING TEASPOON-JASMINE TEST================"
  RAILS_ENV=test bundle exec teaspoon --coverage=default
  echo ""
  echo "==================RUNNING JSHINT========================="
  bundle exec rake jshint
  echo ""
}
