[[ $DEBUG_BASHRC = 1 ]] && echo "    loading login.gov"

# Environment Variables --------------------------------------------------------

echo "login-gov.conf"
export PROJECT_DEV=${HOME}/Documents/Fearless/dev/login-gov
# export RAILS_ROLE=api
export RAILS_SECRET_KEY_BASE=''
export RAILS_AUTH_SECRET_KEY_BASE=''
export RAILS_DB_PASS=''
export CAPYBARA_WAIT_TIME_SECONDS=3.0
# export WEBPACK_PORT=${WEBPACK_PORT:-3035}

export COVERAGE=true
export RACK_TIMEOUT_SERVICE_TIMEOUT=10000

export AWS_PROFILE='login-master'
export AWS_REGION='us-west-2'
export AWS_VAULT_PROPMT=ykman
export AWS_VAULT_KEYCHAIN_NAME=login
export YKMAN_OATH_CREDENTIAL_NAME=$(ykman oath accounts list)
export LOGIN_IAM_PROFILE=power
export AWS_IAM_USER=douglas.price

# For personal environments
export OSXSC_LIB=/usr/lib/ssh-keychain.dylib
export GSA_USERNAME='solipet'
export GSA_FULLNAME='Douglas Price'
export GSA_EMAIL='douglas.price@gsa.gov'
export KITCHEN_EC2_SSH_KEY=~/.ssh/gsa_testkitchen
export KITCHEN_EC2_SSH_KEYPAIR_ID=SOLIPET-TEST-KITCHEN

# If you
# export PATH=/Project/Specific/Paths:$PATH

if [ -z $CDPATH ] ; then
  export CDPATH=.:${PROJECT_DEV}
else
  export CDPATH=${CDPATH}:${PROJECT_DEV}
fi

export PATH=${PROJECT_DEV}/identity-devops/bin:$PATH

# Google API Key
# export GOOGLE_API_KEY='AIzaSyCHxOsL4k6RsDV81Nqro8fmBwz3I1imlWI' # Dougs

# Aliases ----------------------------------------------------------------------
alias bym='bin/bundle install; npm install; bin/rails db:migrate; git restore db/schema.rb'
alias  av='aws-vault exec sandbox-power -- aws '
alias avi='aws-vault exec sandbox-power -- '
alias avilsc='aws-vault exec sandbox-power -- ./bin/ls-servers --compact -e'
alias avipuma='aws-vault exec sandbox-power -- ./bin/idp-config-reload -e'

alias avp='aws-vault exec prod-power -- '
alias avplsc='aws-vault exec prod-power -- ./bin/ls-servers --compact -e'
alias avppuma='aws-vault exec prod-power -- ./bin/idp-config-reload -e'
alias avpuuid='aws-vault exec prod-power -- ./bin/data-pull --any asg-prod-idp uuid-lookup ' # email1@foo.com email2@foo.com ...
alias avpevents='aws-vault exec prod-power -- ./bin/data-pull --any asg-prod-idp events-summary ' # <uuid>

alias avt='aws-vault exec sandbox-terraform -- '
alias avtd='aws-vault exec sandbox-terraform -- ./bin/tf-deploy'


# Functions --------------------------------------------------------------------

function old-pivssh () {
  ssh-add -e /usr/local/lib/opensc-pkcs11.so || true
  while ! ssh-add -L | grep -q opensc; do
    ssh-add -K -s /usr/local/lib/opensc-pkcs11.so
    sleep 1
  done
}

function pivssh () {
  ssh-add -e /usr/lib/ssh-keychain.dylib || true
  while ! ssh-add -L | grep -q ssh-keychain.dylib; do
    ssh-add -K -s /usr/lib/ssh-keychain.dylib
    sleep 1
  done
}

